// Generated by backend/scripts/generate_ws_messages.py; do not edit.

export interface SubscribeMessage {
  type: string;
  topics: string[];
}

export interface SubscriptionAck {
  type: string;
  topics: string[];
}

export interface ToneDiscoveredMessage {
  type: string;
  data: Record<string, unknown>;
}

export type WebSocketMessage = SubscribeMessage | SubscriptionAck | ToneDiscoveredMessage;
