// Generated by backend/scripts/generate_ws_messages.py; do not edit.

export interface SubscribeMessage {
  type: string;
  topics: string[];
}

export interface SubscriptionAck {
  type: string;
  topics: string[];
}

export type WebSocketMessage = SubscribeMessage | SubscriptionAck;
