"""Generate TypeScript WebSocket protocol types from Pydantic models."""

from __future__ import annotations

from pathlib import Path

from tonewatch.api.ws_models import SubscribeMessage, SubscriptionAck


def main() -> None:
    """Generate TypeScript interfaces from the protocol models."""
    models = (SubscribeMessage, SubscriptionAck)
    lines = ["// Generated by backend/scripts/generate_ws_messages.py; do not edit.", ""]
    for model in models:
        schema = model.model_json_schema()
        lines.append(f"export interface {model.__name__} {{")
        for name, prop in schema["properties"].items():
            type_name = "string" if prop.get("type") == "string" else "string[]"
            lines.append(f"  {name}: {type_name};")
        lines.extend(["}", ""])
    lines.append("export type WebSocketMessage = SubscribeMessage | SubscriptionAck;\n")
    output = Path(__file__).parents[2] / "web/src/api/ws-messages.ts"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
