"""PM model ledger: token usage and review outcomes per Codex engineer run.

Sources:
  docs/pm/runs/<brief>-<stamp>.jsonl    codex exec --json event stream (usage, commands)
  docs/pm/reports/<brief>-<stamp>.md    final message; trailer line `model=... effort=...`
  docs/pm/reviews.csv                   PM verdicts (written by the PM after each review)

Writes docs/pm/model-ledger.md. Run: uv run --project backend python docs/pm/ledger.py
"""

from __future__ import annotations

import csv
import json
import re
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

PM = Path(__file__).resolve().parent
RUN_RE = re.compile(r"^(?P<brief>.+)-(?P<stamp>\d{8}-\d{6})$")
# Runs dispatched before the dispatcher recorded model/effort.
LEGACY = {"model": "gpt-5.6-luna", "effort": "medium"}


@dataclass
class Run:
    run_id: str
    brief: str
    milestone: str
    thread: str = ""
    model: str = LEGACY["model"]
    effort: str = LEGACY["effort"]
    resume: bool = False
    minutes: float = 0.0
    input_tokens: int = 0
    cached: int = 0
    output: int = 0
    reasoning: int = 0
    commands: int = 0
    failed_commands: int = 0
    completed: bool = False
    review: dict[str, str] = field(default_factory=dict)

    @property
    def uncached(self) -> int:
        return self.input_tokens - self.cached


def load_reviews() -> dict[str, dict[str, str]]:
    path = PM / "reviews.csv"
    if not path.exists():
        return {}
    with path.open(encoding="utf-8", newline="") as fh:
        return {row["run_id"]: row for row in csv.DictReader(fh)}


def parse_run(log: Path, reviews: dict[str, dict[str, str]]) -> Run | None:
    m = RUN_RE.match(log.stem)
    if not m:
        return None
    brief = m["brief"]
    run = Run(run_id=log.stem, brief=brief, milestone=brief.split("-")[0])
    start = datetime.strptime(m["stamp"], "%Y%m%d-%H%M%S").astimezone()
    run.minutes = round(
        (
            datetime.fromtimestamp(log.stat().st_mtime).astimezone() - start
        ).total_seconds()
        / 60,
        1,
    )
    for line in log.read_text(encoding="utf-8", errors="replace").splitlines():
        try:
            ev = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not isinstance(ev, dict):
            continue
        kind = ev.get("type")
        if kind == "thread.started":
            run.thread = ev.get("thread_id", "")
        elif kind == "turn.completed":
            u = ev.get("usage", {})
            run.input_tokens += u.get("input_tokens", 0)
            run.cached += u.get("cached_input_tokens", 0)
            run.output += u.get("output_tokens", 0)
            run.reasoning += u.get("reasoning_output_tokens", 0)
            run.completed = True
        elif (
            kind == "item.completed"
            and ev.get("item", {}).get("type") == "command_execution"
        ):
            run.commands += 1
            if ev["item"].get("exit_code") not in (0, None):
                run.failed_commands += 1
    report = PM / "reports" / f"{log.stem}.md"
    if report.exists():
        for key, val in re.findall(
            r"(model|effort|resume)=(\S+)", report.read_text(encoding="utf-8")
        ):
            if key == "resume":
                run.resume = val != "new"
            else:
                setattr(run, key, val)
    run.review = reviews.get(run.run_id, {})
    return run


def fmt(n: float) -> str:
    return f"{n / 1e6:.2f}M" if n >= 1e6 else f"{n / 1e3:.1f}k"


def main() -> None:
    reviews = load_reviews()
    runs = [
        r for p in sorted((PM / "runs").glob("*.jsonl")) if (r := parse_run(p, reviews))
    ]
    lines = [
        "# Codex model ledger",
        "",
        "Generated by `docs/pm/ledger.py`. Verdicts come from `docs/pm/reviews.csv`.",
        "**Uncached input + output** is the cost proxy; cached input is cheap.",
        "",
        "## Runs",
        "",
        "| run | model · effort | min | uncached in | output (reasoning) | cmds (failed) | verdict | failure class | findings |",
        "|---|---|--:|--:|--:|--:|---|---|--:|",
    ]
    for r in runs:
        v = r.review
        lines.append(
            f"| {r.run_id} | {r.model} · {r.effort}{' (resume)' if r.resume else ''} | {r.minutes} "
            f"| {fmt(r.uncached)} | {fmt(r.output)} ({fmt(r.reasoning)}) | {r.commands} ({r.failed_commands}) "
            f"| {v.get('verdict', 'pending' if r.completed else 'running')} | {v.get('failure_class', '')} "
            f"| {v.get('findings', '')} |"
        )

    # Per milestone: total cost to acceptance and rounds needed.
    by_ms: dict[str, list[Run]] = defaultdict(list)
    for r in runs:
        by_ms[r.milestone].append(r)
    lines += [
        "",
        "## Cost to acceptance per milestone",
        "",
        "| milestone | rounds | accepted | models used | uncached in | output |",
        "|---|--:|---|---|--:|--:|",
    ]
    for ms, rs in by_ms.items():
        accepted = any(r.review.get("verdict") == "pass" for r in rs)
        models = ", ".join(sorted({f"{r.model}·{r.effort}" for r in rs}))
        lines.append(
            f"| {ms} | {len(rs)} | {'yes' if accepted else 'no'} | {models} "
            f"| {fmt(sum(r.uncached for r in rs))} | {fmt(sum(r.output for r in rs))} |"
        )

    # Per model·effort: how often a run passes review and what it costs.
    by_model: dict[str, list[Run]] = defaultdict(list)
    for r in runs:
        if r.review.get("verdict"):
            by_model[f"{r.model} · {r.effort}"].append(r)
    lines += [
        "",
        "## Model · effort scorecard (reviewed runs only)",
        "",
        "| model · effort | runs | pass rate | design/bug failures | env failures | avg uncached in | avg output |",
        "|---|--:|--:|--:|--:|--:|--:|",
    ]
    for key, rs in sorted(by_model.items()):
        n = len(rs)
        passes = sum(r.review["verdict"] == "pass" for r in rs)
        env = sum(r.review.get("failure_class") == "env" for r in rs)
        work = sum(
            r.review.get("failure_class") in {"design", "bug", "verification", "spec"}
            for r in rs
        )
        lines.append(
            f"| {key} | {n} | {passes / n:.0%} | {work} | {env} "
            f"| {fmt(sum(r.uncached for r in rs) / n)} | {fmt(sum(r.output for r in rs) / n)} |"
        )
    lines += [
        "",
        "Failure classes:",
        "- `env`: sandbox or tooling, not the model's fault; excluded when judging models.",
        "- `verification`: claimed checks it didn't actually run.",
        "- `spec`: missed brief requirements.",
        "- `bug`: defects in the code.",
        "- `design`: wrong approach.",
        "",
    ]
    (PM / "model-ledger.md").write_text(
        "\n".join(lines), encoding="utf-8", newline="\n"
    )
    print(f"ledger: {len(runs)} runs -> docs/pm/model-ledger.md")


if __name__ == "__main__":
    main()
